spring.application.name=apiPenduraAi

spring.datasource.url=jdbc:postgresql://localhost:5432/api_pendura_ai
spring.datasource.username=postgres
spring.datasource.password=Password123#@!
spring.jpa.show-sql=true

jwt.secret=T3ST3
auth.cookie.secure=false
app.cors.allowed-origins=http://localhost:4200

spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=50